# Generated by Django 4.2.10 on 2024-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(default="", max_length=64)),
                ("email", models.CharField(default="", max_length=64)),
                ("vehicle_make", models.CharField(default="", max_length=64)),
                ("vehicle_model", models.CharField(default="", max_length=64)),
                ("vehicle_color", models.CharField(default="", max_length=64)),
                ("origination_state", models.CharField(max_length=64)),
                ("destination_city", models.CharField(max_length=64)),
                ("destination_state", models.CharField(max_length=2)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("taking_passengers", models.BooleanField(default=False)),
                ("seats_available", models.IntegerField(default=0)),
            ],
        ),
    ]
