# Generated by Django 4.2.11 on 2024-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_alter_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
