# Generated by Django 4.2.11 on 2024-05-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_alter_person_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="origination_state",
            new_name="origination",
        ),
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="person",
            name="vehicle_color",
        ),
        migrations.RemoveField(
            model_name="person",
            name="vehicle_make",
        ),
        migrations.RemoveField(
            model_name="person",
            name="vehicle_model",
        ),
    ]
